name: Run .NET Build and Test

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: ./.github/actions/setup-dotnet
    - run: dotnet build -c Release -t:build,pack
    - run: dotnet test -c Release --no-build
