name: unity

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  unity:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - uses: actions/setup-dotnet@v3
      with:
        global-json-file: global.json
    - run: dotnet build -c Debug
    
    - uses: actions/cache@v3
      with:
        path: src/MessagePack.UnityClient/Library
        key: MessagePack-ubuntu

    - uses: Cysharp/Actions/.github/actions/check-metas@main # check meta files
      with:
        directory: src/MessagePack.UnityClient

    - name: Build project
      uses: game-ci/unity-builder@v4
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      with:
        projectPath: src/MessagePack.UnityClient
        unityVersion: 2022.3.12f1
        targetPlatform: StandaloneLinux64
        buildMethod: PackageExporter.Export
        customParameters: /headless /ScriptBackend mono
        versioning: None
